### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by afuh**

### CODE REVIEW

**Comment by spielhoelle** [comment]
Really nice code!
Please create example content for  in variables.env.default (CLIENT_ID=xxxxxxx), and maybe with a hint in README.md like:
> place the CLIENT_ID from https://github.com/organizations/devugees/settings/applications/595813

Login view with github seems to work, but after redirect i got this, ouch.
bildschirmfoto 2017-09-28 um 21 02 14

No pressure - don't forget its weekend <3

**Comment by afuh** [comment]
Of course! I totally forgot the `variables.env.default` file, will do it tomorrow and check for that error.

**Comment by ayhamthemayhem** [comment]
Aswome work man !! 
meme-functions

**Comment by spielhoelle** [comment]
Lol!
1979468_10152812145256840_5988845449444092332_n

**Comment by spielhoelle** [comment]
Really awesome - looks like it works. 
I merge and we talk Wednesday about restricting parts of the frontend completely and also apply it for some isLoggedIn routes/methods

**Pull request merged**
